import "./globals.css";
import ReactQueryProvider from "./components/ReactQueryProvider/ReactQueryProvider";
import { EB_Garamond } from '@next/font/google'; 

const EBGaramond = EB_Garamond({subsets: ['latin']});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <ReactQueryProvider>
    <html lang="en">
      <body className={EBGaramond.className}>
        {children}
        </body>
    </html>
    </ReactQueryProvider>
  );
}
